function isValidQuestion(question: string): boolean {
    const minLength = 25; // Numerical questions are usually longer than 15 chars
    const maxLength = 800; // Math questions with LaTeX can be long

    // Check for actual letters
    const hasContent = /[a-z]{3,}/i.test(question);

    // EXCLUDE HEADERS AND BRANDING
    const isNotHeader = !/^(QUESTION|SECTION|TIME|HOURS|INSTRUCTIONS)/i.test(
        question.trim()
    );
    const isNotBranding = !/(Generated by|Tidy Up|Contact:|@gmail)/i.test(
        question
    );

    // Exclude common fragments
    const notFragment =
        !/^(Here's|Please|These are|Models are|Analyze|Explain|Following|Below)$/i.test(
            question.trim().split(' ')[0] // Check the first word
        );

    return (
        question.length >= minLength &&
        question.length <= maxLength &&
        hasContent &&
        isNotHeader &&
        isNotBranding &&
        notFragment
    );
}
export default isValidQuestion;
