import PDFDocument from 'pdfkit';
import fs from 'fs-extra';
import createLogger from './logger.js';

const log = createLogger('Pdf generator');
interface MergedQuestions {
    text: string;
    source: string;
}
export default async function generatePDF(
    questions: MergedQuestions[],
    outputPath: string,
    isWorkSheet: boolean = false
) {
    return new Promise<void>((resolve, reject) => {
        log.highlight('generating pdf');
        const doc = new PDFDocument({
            size: 'A4',
            bufferPages: true, //allows to add page numbers at the end
            margin: 50,
        });
        const stream = fs.createWriteStream(outputPath);
        doc.pipe(stream);
        // --- PAGE 1: COVER & STATISTICS ---
        doc.rect(0, 0, 595, 100).fill('#2c3e50'); // Dark header bar
        doc.fillColor('#ffffff').fontSize(25).text('Tidy-Up Exam Prep', 50, 40);

        doc.moveDown(4);
        doc.fillColor('#2c3e50')
            .fontSize(18)
            .text('Study Guide Summary', { underline: true });
        doc.moveDown(1);

        // Calculate Stats
        const totalQuestions = questions.length;
        const sources = [...new Set(questions.map((q) => q.source))];

        doc.fontSize(12).fillColor('#34495e');
        doc.text(`Total Unique Questions Found: ${totalQuestions}`);
        doc.text(`Total Topics/Files Merged: ${sources.length}`);
        doc.moveDown(1);

        // FIXED LINE HERE
        doc.font('Helvetica-Bold').text('Breakdown by Source:');

        // Reset font to normal for the list
        doc.font('Helvetica');
        sources.forEach((source) => {
            const count = questions.filter((q) => q.source === source).length;
            doc.fontSize(10)
                .fillColor('#7f8c8d')
                .text(`• ${source}: ${count} questions`);
        });

        doc.addPage(); // Move to the actual questions
        questions.forEach((question, indx) => {
            const questionText = `${indx + 1}. ${question.text.trim()}`;

            // If worksheet, we need extra space for students to write
            const spacing = isWorkSheet ? 120 : 15;
            const heightNeeded = doc.heightOfString(questionText, {
                width: 495,
            });

            if (doc.y + heightNeeded + spacing > 750) {
                doc.addPage();
            }

            doc.fillColor('#000000').fontSize(12).text(questionText, {
                align: 'left',
                lineGap: 4,
                paragraphGap: 10,
            });

            if (isWorkSheet) {
                doc.moveDown(5); // Space for answers
                doc.rect(doc.x, doc.y, 495, 80).stroke('#eeeeee'); // Optional: Light box for answers
                doc.moveDown(2);
            }

            doc.moveDown(0.5);
        });
        const pages = doc.bufferedPageRange();
        for (let i = 0; i < pages.count; i++) {
            doc.switchToPage(i);

            // 1. Diagonal Watermark "Tidy Up"
            doc.save()
                .fillColor('#eeeeee')
                .opacity(0.2)
                .fontSize(60)
                .rotate(-45, { origin: [300, 400] })
                .text('TIDY UP', 150, 400)
                .restore();

            // 2. Footer (Name, Phone, Email)
            const footerY = 780;
            doc.fontSize(8).fillColor('#95a5a6').opacity(1);
            doc.text(
                'Generated by Tidy Up | Contact: +254 113868425 | phinjugushdev@gmail.com',
                50,
                footerY,
                {
                    align: 'center',
                    width: 500,
                }
            );
        }
        doc.end();
        stream.on('finish', () => {
            log.highlight(
                'Done generating pdf for backend to send url to frontend'
            );
            resolve();
        });
        stream.on('error', (streamError) => {
            log.error('PDF stream error', { data: { streamError } });
            reject(streamError);
        });
    });
}
